[pytest]
markers =
    smoke: Дымовые тесты
    regression: Регрессионные тесты
    slow: Медленные тесты

addopts =
    -v
    -ra
    --strict-markers
    --cov=src
    --cov-report=term-missing

testpaths = tests