name: Python Tests

on:
  push:
    branches: [ "main", "develop" ] # Запуск при пуше в main или develop
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest # Тесты лучше гонять на linux (быстрее и дешевле), pytest везде одинаков

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12" # Ваша версия из логов PowerShell

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: pytest -v
